# Generated by Django 3.1.4 on 2021-04-15 14:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lectures'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lectures',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='lectures',
            name='subject',
            field=models.CharField(default='Add here', max_length=200),
        ),
    ]
