# Generated by Django 3.1.4 on 2021-04-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210415_1941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lectures',
            managers=[
            ],
        ),
    ]
